### ISSUE TITLE
Future improvements: For m-agent

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/m-agent#2]
Future improvements:
1. M-agent maybe killed which will cause the experiment to block, need some timeout/liveliness check
2. Give option for dynamic port selection for m-agent server
3. Better to have a single endpoint for all experiments and then multiplex on it, makes things much simple and makes the connection re-usable for more complex chaos scenarios.
4. Stdout and Stderr in cmdProbe ambiguity, we are currently only checking stdout for cmd probe but it might happen that the command executed logs info to stderr too
5. Ambigous IP address resolution, document it!

_Originally posted by @gdsoumya in https://github.com/litmuschaos/m-agent/pull/1#pullrequestreview-854578632_

**Comment by neelanjan00** [comment]
Further future improvements:

1. Create a custom cmd probe for Litmusd
2. Create username-password auth
3. Include shell-lint in workflows 
4. Refactor Installation script to create a separate log file for m-agent and update the systemd unit file to redirect the logs to it. 
5. Develop Stress chaos experiment 
6. Create troubleshooting and contributing docs
